{
 "title": "Ceph Pool Details",
 "tags": [ "linked" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pool_name",
    "label": "Pool Name",
    "query": {
     "query": "label_values(ceph_pool_metadata, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pool Configuration Information",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ceph_pool_metadata", "legendFormat": "__auto" },
    { "expr": "ceph_pool_bytes_used", "legendFormat": "__auto" },
    { "expr": "ceph_pool_max_avail", "legendFormat": "__auto" },
    { "expr": "ceph_pool_percent_used", "legendFormat": "__auto" },
    {
     "expr": "ceph_pool_compress_under_bytes - ceph_pool_compress_bytes_used",
     "legendFormat": "__auto"
    },
    {
     "expr": "ceph_pool_recovering_bytes_per_sec",
     "legendFormat": "__auto"
    },
    { "expr": "ceph_pg_total", "legendFormat": "__auto" },
    { "expr": "ceph_pool_quota_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IOPS for Pool : $pool_name",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(ceph_pool_rd[65s]) * on(pool_id) ceph_pool_metadata{name=\"$pool_name\"}",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(ceph_pool_wr[65s]) * on(pool_id) ceph_pool_metadata{name=\"$pool_name\"}",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Pool Capacity Usage: $pool_name",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ceph_pool_stored * on(pool_id) ceph_pool_metadata{name=\"$pool_name\"}",
     "legendFormat": "Logical Used"
    },
    {
     "expr": "ceph_pool_stored_raw * on(pool_id) ceph_pool_metadata{name=\"$pool_name\"}",
     "legendFormat": "Physical Used"
    }
   ]
  },
  {
   "title": "Throughput for Pool : $pool_name",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(ceph_pool_rd_bytes[65s]) * on(pool_id) ceph_pool_metadata{name=\"$pool_name\"}",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(ceph_pool_wr_bytes[65s]) * on(pool_id) ceph_pool_metadata{name=\"$pool_name\"}",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Pool Recovery Activity: $pool_name",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "ceph_pool_recovering_bytes_per_sec * on(pool_id) ceph_pool_metadata{name=\"$pool_name\"}",
     "legendFormat": "Recovery Rate"
    }
   ]
  }
 ]
}