{
 "title": "Ceph Capacity Analysis",
 "tags": [ "linked" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "osd_id",
    "label": "OSD",
    "query": {
     "query": "label_values(ceph_osd_metadata, ceph_daemon)"
    }
   },
   {
    "name": "device_class",
    "label": "Device Type",
    "query": {
     "query": "label_values(ceph_osd_metadata,device_class)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Raw Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_osd_stat_bytes)" }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes - ceph_cluster_total_used_raw_bytes",
     "legendFormat": "Raw Available"
    },
    {
     "expr": "ceph_cluster_by_class_total_used_raw_bytes",
     "legendFormat": "Raw Used"
    }
   ]
  },
  {
   "title": "OSD Usage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "ceph_osd_stat_bytes_used", "legendFormat": "{{ceph_daemon}}" }
   ]
  },
  {
   "title": "Primary PGs by OSD",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "ceph_osd_numpg" }
   ]
  },
  {
   "title": "OSD Devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_metadata{device_class=\"hdd\"}) or vector(0)",
     "legendFormat": "HDD"
    },
    {
     "expr": "count(ceph_osd_metadata{device_class=\"ssd\"}) or vector(0)",
     "legendFormat": "SSD"
    }
   ]
  },
  {
   "title": "OSD Capacity",
   "type": "stat",
   "description": "Summarize the capacity used across all OSDs",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "min(ceph_osd_stat_bytes_used)", "legendFormat": "Min" },
    { "expr": "max(ceph_osd_stat_bytes_used)", "legendFormat": "Max" },
    {
     "expr": "stddev(ceph_osd_stat_bytes_used)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capacity Usage for '$device_class' OSDs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes_used{ceph_daemon=~\"$osd_id\"} * on(ceph_daemon) group_left ceph_osd_metadata{device_class=~\"$device_class\"}",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "Bluefs Usage for '$device_class' OSDs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ceph_bluefs_db_used_bytes * on(ceph_daemon) group_left ceph_osd_metadata{device_class=~\"$device_class\"}",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "RAW Capacity Usage By Pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 2, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ceph_pool_stored_raw * on(pool_id) group_right ceph_pool_metadata",
     "legendFormat": "{{name}}"
    },
    { "expr": "ceph_cluster_total_bytes", "legendFormat": "Total Capacity" }
   ]
  }
 ]
}