{
 "title": "Ceph OSD Performance",
 "tags": [ "linked" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "osd_id",
    "label": "OSD Id",
    "query": {
     "query": "label_values(ceph_osd_metadata, ceph_daemon)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OSD Activity - $osd_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "OSD Read OPs - $osd_id",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_r{ceph_daemon=~\"$osd_id\"}[1m])",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "OSD Write OPs - $osd_id",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_w{ceph_daemon=~\"$osd_id\"}[1m])",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "OSD Apply",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ceph_osd_apply_latency_ms{ceph_daemon=~\"$osd_id\"}",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "OSD Read OP Latency - $osd_id",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_r_latency_sum[1m]) / rate(ceph_osd_op_r_latency_count{ceph_daemon=~\"$osd_id\"}[1m])",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "OSD Write OP Latency - $osd_id",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_w_latency_sum[1m]) / rate(ceph_osd_op_w_latency_count{ceph_daemon=~\"$osd_id\"}[1m])",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "OSD Commit",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ceph_osd_commit_latency_ms{ceph_daemon=~\"$osd_id\"}",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "OSD Read Throughput - $osd_id",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_r_out_bytes{ceph_daemon=~\"$osd_id\"}[1m])",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "OSD Write Throughput - $osd_id",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_w_in_bytes{ceph_daemon=~\"$osd_id\"}[1m])",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Physical Disk Activity - $osd_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Physical Read IOPS - $osd_id",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "topk(10,(rate(node_disk_reads_completed_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation{ceph_daemon=~\"$osd_id\"}, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\")))",
       "legendFormat": "{{ ceph_daemon  }} / {{ device }}"
      },
      {
       "expr": "sum(rate(node_disk_reads_completed_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\"))",
       "legendFormat": "Total Read IOPS"
      }
     ]
    },
    {
     "title": "Physical Write IOPS - $osd_id",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "topk(10,(rate(node_disk_writes_completed_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation{ceph_daemon=~\"$osd_id\"}, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\")))",
       "legendFormat": "{{ ceph_daemon  }} / {{ device }}"
      },
      {
       "expr": "sum(rate(node_disk_writes_completed_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\"))",
       "legendFormat": "Total Write IOPS"
      }
     ]
    },
    {
     "title": "Physical READ Latencies",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(rate(node_disk_read_time_seconds_total[1m]) / clamp_min(rate(node_disk_reads_completed_total[1m]),1)) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation{ceph_daemon=~\"$osd_id\"}, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\")",
       "legendFormat": "{{ ceph_daemon  }} / {{ device }}"
      }
     ]
    },
    {
     "title": "Physical WRITE Latencies - $osd_id",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(rate(node_disk_write_time_seconds_total[1m]) / clamp_min(rate(node_disk_writes_completed_total[1m]),1)) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation{ceph_daemon=~\"$osd_id\"}, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\")",
       "legendFormat": "{{ ceph_daemon  }} / {{ device }}"
      }
     ]
    },
    {
     "title": "Physical READ Throughput - $osd_id",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation{ceph_daemon=~\"$osd_id\"}, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\")",
       "legendFormat": "{{ ceph_daemon  }} / {{ device }}"
      },
      {
       "expr": "sum(rate(node_disk_read_bytes_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\"))",
       "legendFormat": "Total READ Throughput"
      }
     ]
    },
    {
     "title": "Physical WRITE Throughput - $osd_id",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(node_disk_written_bytes_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation{ceph_daemon=~\"$osd_id\"}, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\")",
       "legendFormat": "{{ ceph_daemon  }} / {{ device }}"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\"))",
       "legendFormat": "Total Write Throughput"
      }
     ]
    },
    {
     "title": "Average Read IO Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(rate(node_disk_read_bytes_total[1m]) / rate(node_disk_reads_completed_total[1m]) ) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation{ceph_daemon=~\"$osd_id\"}, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\") ",
       "legendFormat": "{{ceph_daemon}}/{{device}}"
      }
     ]
    },
    {
     "title": "Average Write IO Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(rate(node_disk_written_bytes_total[1m]) / rate(node_disk_writes_completed_total[1m]) ) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation{ceph_daemon=~\"$osd_id\"}, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\")",
       "legendFormat": "{{ceph_daemon}}/{{device}}"
      }
     ]
    }
   ]
  }
 ]
}