{
 "title": "Ceph Placement Groups",
 "tags": [ "linked" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pool_id",
    "query": {
     "query": "label_values(ceph_pool_metadata, pool_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "PG Distribution per OSD",
   "type": "stat",
   "description": "Summarize the capacity used across all OSDs",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "min(ceph_osd_numpg)", "legendFormat": "Min" },
    { "expr": "max(ceph_osd_numpg)", "legendFormat": "Max" },
    { "expr": "stddev(ceph_osd_numpg)", "legendFormat": "STD Dev" }
   ]
  },
  {
   "title": "Primary PGs by OSD",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "ceph_osd_numpg" }
   ]
  },
  {
   "title": "PG Count by Pools",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ceph_pg_total * on(pool_id) group_right ceph_pool_metadata",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PG States by Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "(ceph_pg_active and ceph_pg_clean) * on(pool_id) group_right ceph_pool_metadata",
     "legendFormat": "{{name}} Active+Clean"
    },
    { "legendFormat": "__auto" }
   ]
  }
 ]
}