{
 "title": "Client Performance",
 "tags": [ "linked" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pvc",
    "label": "PVC Name",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{storageclass=~\"ocs-storagecluster.*\"},persistentvolumeclaim)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\"}"
    }
   ]
  },
  {
   "title": "PVC IOPS : $pvc",
   "type": "timeseries",
   "description": "Needs the rbd_stats_pools set in mgr/prometheus",
   "gridPos": { "h": 12, "w": 7, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "round(rate(ceph_rbd_read_ops[30s]),1)  * on(image) group_left(volumename) label_replace(ocs_rbd_pv_metadata,\"volumename\",\"$1\",\"name\",\"(.*)\") * on(volumename) group_left(persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=~\"$pvc\"}",
     "legendFormat": "{{persistentvolumeclaim}}(R)"
    },
    {
     "expr": "round(rate(ceph_rbd_write_ops[30s]),1) * on(image) group_left(volumename) label_replace(ocs_rbd_pv_metadata,\"volumename\",\"$1\",\"name\",\"(.*)\") * on(volumename) group_left(persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=~\"$pvc\"}",
     "legendFormat": "{{persistentvolumeclaim}}(W)"
    }
   ]
  },
  {
   "title": "PVC Throughput : $pvc",
   "type": "timeseries",
   "description": "Needs the rbd_stats_pools set in mgr/prometheus",
   "gridPos": { "h": 12, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "round(rate(ceph_rbd_read_bytes[30s]),1)  * on(image) group_left(volumename) label_replace(ocs_rbd_pv_metadata,\"volumename\",\"$1\",\"name\",\"(.*)\") * on(volumename) group_left(persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=~\"$pvc\"}",
     "legendFormat": "{{persistentvolumeclaim}}(R)"
    },
    {
     "expr": "round(rate(ceph_rbd_write_bytes[30s]),1) * on(image) group_left(volumename) label_replace(ocs_rbd_pv_metadata,\"volumename\",\"$1\",\"name\",\"(.*)\") * on(volumename) group_left(persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=~\"$pvc\"}",
     "legendFormat": "{{persistentvolumeclaim}}(W)"
    }
   ]
  },
  {
   "title": "PVC Latency : $pvc",
   "type": "timeseries",
   "description": "Needs the rbd_stats_pools set in mgr/prometheus",
   "gridPos": { "h": 12, "w": 7, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "(rate(ceph_rbd_read_latency_sum[30s]) / clamp_min(rate(ceph_rbd_read_latency_count[30s]),1))  * on(image) group_left(volumename) label_replace(ocs_rbd_pv_metadata,\"volumename\",\"$1\",\"name\",\"(.*)\") * on(volumename) group_left(persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=~\"$pvc\"}",
     "legendFormat": "{{persistentvolumeclaim}}(R)"
    },
    {
     "expr": "(rate(ceph_rbd_write_latency_sum[30s]) / clamp_min(rate(ceph_rbd_write_latency_count[30s]),1))  * on(image) group_left(volumename) label_replace(ocs_rbd_pv_metadata,\"volumename\",\"$1\",\"name\",\"(.*)\") * on(volumename) group_left(persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=~\"$pvc\"}",
     "legendFormat": "{{persistentvolumeclaim}}(W)"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "description": "As  reported by kubelet",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc\"}"
    }
   ]
  },
  {
   "title": "PVC Utilisation",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\"}"
    }
   ]
  },
  {
   "title": "RBD metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(rate(node_disk_read_time_seconds_total{device=~\"rbd.*\"}[1m]) / clamp_min(rate(node_disk_reads_completed_total[1m]),1))",
       "legendFormat": "read"
      },
      {
       "expr": "(rate(node_disk_write_time_seconds_total{device=~\"rbd.*\"}[1m]) / clamp_min(rate(node_disk_writes_completed_total[1m]),1))",
       "legendFormat": "write"
      },
      {
       "expr": "(rate(node_disk_read_time_seconds_total{device=~\"rbd*\"}[1ms]) / clamp_min(rate(node_disk_reads_completed_total[1m]),1))",
       "legendFormat": "read"
      }
     ]
    },
    {
     "title": "Client IOPS (rbd* devices)",
     "type": "timeseries",
     "description": "Total of IOPS for rbd devices within the cluster",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "round(sum(rate(node_disk_reads_completed_total{device=~\"rbd.*\"}[1m])),1)",
       "legendFormat": "Reads"
      },
      {
       "expr": "round(sum(rate(node_disk_writes_completed_total{device=~\"rbd.*\"}[1m])),1)",
       "legendFormat": "Writes"
      }
     ]
    }
   ]
  },
  {
   "title": "Panel testing - TO DELETE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "PVC  IOPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "label_replace((label_replace(kube_persistentvolumeclaim_info{storageclass=~\"ocs.*\",persistentvolumeclaim=~\"$pvc\"},\"persistentvolume\", \"$1\", \"volumename\", \"(.*)\") * on(persistentvolume) group_right(persistentvolumeclaim) kube_persistentvolume_info),\"image\", \"csi-vol-$2\", \"csi_volume_handle\", \".*openshift-storage-(\\\\d+)-(.*)\") * on(image) rate(ceph_rbd_read_ops[1m])",
       "legendFormat": "Reads"
      },
      {
       "expr": "label_replace((label_replace(kube_persistentvolumeclaim_info{storageclass=~\"ocs.*\",persistentvolumeclaim=~\"$pvc\"},\"persistentvolume\", \"$1\", \"volumename\", \"(.*)\") * on(persistentvolume) group_right(persistentvolumeclaim) kube_persistentvolume_info),\"image\", \"csi-vol-$2\", \"csi_volume_handle\", \".*openshift-storage-(\\\\d+)-(.*)\") * on(image) rate(ceph_rbd_write_ops[1m])",
       "legendFormat": "Writes"
      }
     ]
    }
   ]
  }
 ]
}