{
 "title": "Host Information",
 "tags": [ "linked" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "worker",
    "label": "Worker",
    "query": {
     "query": "label_values(kube_node_role{role=~'(worker|infra)'}, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Host CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100 )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total IOPS by Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_disk_writes_completed_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\")) + sum by(instance) (rate(node_disk_reads_completed_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\"))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Network Bandwidth by Host",
   "type": "timeseries",
   "description": "Network receive + transmit bytes for all active (UP) physical interfaces on each host in the cluster",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(sum by(instance) (rate(node_network_receive_bytes_total{device=~\"(eth|en).*\"}[1m]) * on(instance, device) node_network_info{operstate=\"up\"})) +\n(sum by(instance) (rate(node_network_transmit_bytes_total{device=~\"(eth|en).*\"}[1m]) * on(instance, device) node_network_info{operstate=\"up\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Host RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Disk Bandwidth by Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_disk_written_bytes_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\")) + sum by(instance) (rate(node_disk_read_bytes_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\"))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Load : $worker",
   "type": "timeseries",
   "description": "Network receive + transmit bytes for all active (UP) physical interfaces on each host in the cluster",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(rate(node_network_receive_bytes_total{instance=\"$worker\",device=~\"(eth|en).*\"}[1m]) * on(instance, device) node_network_info{operstate=\"up\"})",
     "legendFormat": "{{device}}/RX"
    },
    {
     "expr": "(rate(node_network_transmit_bytes_total{instance=\"$worker\",device=~\"(eth|en).*\"}[1m]) * on(instance, device) node_network_info{operstate=\"up\"}) * -1",
     "legendFormat": "{{device}}/TX"
    }
   ]
  }
 ]
}