{
 "title": "ODF Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "worker",
    "label": "Worker",
    "query": {
     "query": "label_values(kube_node_role{role=~'(worker|infra)'}, node)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "rbd_device",
    "label": "rbd Device",
    "query": {
     "query": "label_values(node_disk_read_bytes_total{instance=~\"$worker.*\", device=~\"rbd.*\"}, device)"
    }
   },
   {
    "name": "pvc",
    "label": "ODF PVC name",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{storageclass=~\"ocs-storagecluster.*\"},persistentvolumeclaim)"
    }
   },
   {
    "name": "ocs_version",
    "query": {
     "query": "label_values(ocs_exporter_version, version)"
    }
   },
   {
    "name": "ceph_version",
    "query": {
     "query": "label_values(ceph_mon_metadata, ceph_version)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ceph Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_health_status" }
   ]
  },
  {
   "title": "HealthCheck History",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 10, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "ceph_health_detail{severity=\"HEALTH_WARN\"} > 0",
     "legendFormat": "{{name}}"
    },
    { "expr": "sum(ceph_health_detail) == 0", "legendFormat": "HEALTH_OK" },
    {
     "expr": "(ceph_health_detail{severity=\"HEALTH_ERR\"} > 0) + 1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Ceph CPU Core Usage",
   "type": "timeseries",
   "description": "Includes mgr,mons,osds and rbd-mirror daemons",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(label_replace(rate(container_cpu_usage_seconds_total{image!=\"\",container=~\"osd|rbd-mirror|mgr|mon|mds|rgw\", namespace=\"openshift-storage\"}[2m]),\"daemon\", \"$1\", \"pod\", \"rook-ceph-(.*)\"))",
     "legendFormat": "Total CPU"
    }
   ]
  },
  {
   "title": "OCS Version",
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "options": {
    "content": "<br>\n<center><h1>${ocs_version}</h1></center>"
   }
  },
  {
   "title": "Ceph Version",
   "type": "text",
   "description": "ceph version based on the version running in the monitors",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 7 },
   "options": {
    "content": "<br>\n<center><h1>${ceph_version}</h1></center>"
   }
  },
  {
   "title": "OSD Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(exported_instance) (ceph_disk_occupation))"
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(ceph_osd_metadata)" }
   ]
  },
  {
   "title": "OSD Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(ceph_osd_stat_bytes)" }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes - ceph_cluster_total_used_raw_bytes",
     "legendFormat": "Raw Available"
    },
    {
     "expr": "ceph_cluster_by_class_total_used_raw_bytes",
     "legendFormat": "Raw Used"
    }
   ]
  },
  {
   "title": "Cluster IOPS by Pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "round(((rate(ceph_pool_rd[65s]) + rate(ceph_pool_wr[65s])) * on(pool_id) group_left(name) (ceph_pool_metadata)),1)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Raw Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_osd_stat_bytes)" }
   ]
  },
  {
   "title": "OSD States",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up == 1 and ceph_osd_in == 1)",
     "legendFormat": "Healthy"
    },
    {
     "expr": "count(ceph_osd_up != 1 or ceph_osd_in != 1) or vector(0)",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "PGs / OSD",
   "type": "stat",
   "description": "Average PG's per OSD",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pg_total) / count(ceph_osd_metadata)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSD Devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_metadata{device_class=\"hdd\"}) or vector(0)",
     "legendFormat": "HDD"
    },
    {
     "expr": "count(ceph_osd_metadata{device_class=\"ssd\"}) or vector(0)",
     "legendFormat": "SSD"
    }
   ]
  },
  {
   "title": "Cluster Throughput by Pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(rate(ceph_pool_rd_bytes[65s]) + rate(ceph_pool_wr_bytes[65s])) * on(pool_id) group_left(name) (ceph_pool_metadata)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(ceph_pool_metadata)" }
   ]
  },
  {
   "title": "Storageclasses",
   "type": "stat",
   "description": "ODF (noobaa and ceph) storage classes",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_storageclass_info{provisioner=~\"openshift-storage.*\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "PV Counts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info{storageclass=\"ocs-storagecluster-ceph-rbd\"}) or vector(0)",
     "legendFormat": "Block"
    },
    {
     "expr": "count(kube_persistentvolumeclaim_info{storageclass=\"ocs-storagecluster-cephfs\"}) or vector(0)",
     "legendFormat": "File"
    }
   ]
  },
  {
   "title": "RGW Daemons",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_rgw_metadata) or vector(0)"
    }
   ]
  },
  {
   "title": "RBD-Mirror",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(0)" }
   ]
  },
  {
   "title": "Noobaa Endpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(0)" }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 19 }, "options": { "content": "<br>\n<br>\n  CPU Limits\n\n\n" } },
  {
   "title": "OSD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_resource_limit{resource=\"cpu\",namespace=\"openshift-storage\",pod=~\"osd.*\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Monitor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_resource_limit{resource=\"cpu\",namespace=\"openshift-storage\",pod=~\"mon.*\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Noobaa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_resource_limit{resource=\"cpu\",namespace=\"openshift-storage\",pod=~\"noobaa.*\"}) or vector(0)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 2, "x": 10, "y": 19 }, "options": { "content": "\n\n\n" } }
 ]
}