{
 "title": "OCP Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "OCP Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "topk(1,label_replace(openshift_apiserver_build_info,\"ocp_version\", \"$1\", \"gitVersion\",\"(.*)-(.*)-(.*)\"))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Alerts",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ALERTS{alertstate=\"firing\"})"
      }
     ]
    },
    {
     "title": "OCP Nodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count(kube_node_info)" }
     ]
    },
    {
     "title": "Namespaces",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_namespace_status_phase{phase=\"Active\"})"
      }
     ]
    },
    {
     "title": "Service Routes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count(openshift_route_info)" }
     ]
    },
    {
     "title": "PODs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count(kube_pod_info)" }
     ]
    },
    {
     "title": "StorageClasses",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count(kube_storageclass_info)" }
     ]
    },
    {
     "title": "PVCs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_persistentvolumeclaim_info)"
      }
     ]
    },
    {
     "title": "PVC Usage",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim!~\"ocs-deviceset.*\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "sum(kubelet_volume_stats_used_bytes{persistentvolumeclaim!~\"ocs-deviceset.*\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(100 - (avg by(instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[30s])) * 100) * on(instance) group_left(role) label_replace(kube_node_role{role=\"master\"},\"instance\", \"$1\", \"node\",\"(.*)\"))"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(100 - (avg by(instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[30s])) * 100) * on(instance) group_left(role) label_replace(kube_node_role{role=\"worker\"},\"instance\", \"$1\", \"node\",\"(.*)\"))"
      }
     ]
    },
    { "title": "OCP Alert Summary", "type": "alertlist", "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 } },
    {
     "title": "Node Configuration Summary",
     "type": "table",
     "gridPos": { "h": 10, "w": 15, "x": 8, "y": 5 },
     "targets": [
      { "expr": "node_cpu_info" },
      { "expr": "node_memory_MemTotal_bytes" },
      {
       "expr": "label_replace(kube_node_role,\"instance\", \"$1\", \"node\", \"(.*)\")"
      },
      {
       "expr": "count by(instance) (node_network_device_id{device!~\"lo|vx.*|tun.*|br.*|ovs.*\"})"
      },
      {
       "expr": "count by(instance) (label_replace(kube_pod_info, \"instance\", \"$1\", \"node\", \"(.*)\"))"
      },
      {
       "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[30s])) * 100)"
      }
     ]
    }
   ]
  }
 ]
}