{
 "title": "ODF Performance Analysis",
 "time": { "from": "2022-09-15T04:00:00.000Z", "to": "2022-09-15T12:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "worker",
    "label": "Worker",
    "query": {
     "query": "label_values(kube_node_role{role=~'(worker|infra)'}, node)"
    }
   },
   {
    "name": "rbd_device",
    "label": "rbd Device",
    "query": {
     "query": "label_values(node_disk_read_bytes_total{instance=~\"$worker.*\", device=~\"rbd.*\"}, device)"
    }
   },
   {
    "name": "pvc",
    "label": "ODF PVC Name",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{storageclass=~\"ocs-storagecluster.*\"},persistentvolumeclaim)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "ocs_version",
    "query": {
     "query": "label_values(ocs_exporter_version, version)"
    }
   },
   {
    "name": "ceph_version",
    "query": {
     "query": "label_values(ceph_mon_metadata, ceph_version)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ceph Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ceph Health",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "ceph_health_status" }
     ]
    },
    {
     "title": "OCS Version",
     "type": "text",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
     "options": {
      "content": "<br>\n<center><h1>${ocs_version}</h1></center>"
     }
    },
    {
     "title": "Ceph Version",
     "type": "text",
     "description": "ceph version based on the version running in the monitors",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
     "options": {
      "content": "<br>\n<center><h1>${ceph_version}</h1></center>"
     }
    },
    {
     "title": "OSD Nodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count by(exported_instance) (ceph_disk_occupation))"
      }
     ]
    },
    {
     "title": "OSDs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count(ceph_osd_metadata)" }
     ]
    },
    {
     "title": "OSD Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "max(ceph_osd_stat_bytes)" }
     ]
    },
    {
     "title": "Raw Capacity",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(ceph_osd_stat_bytes)" }
     ]
    },
    {
     "title": "Pools",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count(ceph_pool_metadata)" }
     ]
    },
    {
     "title": "Storageclasses",
     "type": "stat",
     "description": "ODF (noobaa and ceph) storage classes",
     "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_storageclass_info{provisioner=~\"openshift-storage.*\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "RBD PV Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_persistentvolumeclaim_info{storageclass=\"ocs-storagecluster-ceph-rbd\"})"
      }
     ]
    },
    {
     "title": "cephfs PV Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_persistentvolumeclaim_info{storageclass=\"ocs-storagecluster-cephfs\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Total Ceph CPU Core Usage",
     "type": "timeseries",
     "description": "Includes mgr,mons,osds and rbd-mirror daemons",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(label_replace(rate(container_cpu_usage_seconds_total{image!=\"\",container=~\"osd|rbd-mirror|mgr|mon|mds\", namespace=\"openshift-storage\"}[1m]),\"daemon\", \"$1\", \"pod\", \"rook-ceph-(.*)\"))",
       "legendFormat": "Total CPU"
      }
     ]
    },
    {
     "title": "Cluster IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "round(((rate(ceph_pool_rd[65s]) + rate(ceph_pool_wr[65s])) * on(pool_id) group_left(name) (ceph_pool_metadata)),1)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Cluster Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(rate(ceph_pool_rd_bytes[65s]) + rate(ceph_pool_wr_bytes[65s])) * on(pool_id) group_left(name) (ceph_pool_metadata)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Cluster Capacity Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "ceph_cluster_total_bytes", "legendFormat": "Total Raw" },
      {
       "expr": "ceph_cluster_total_used_raw_bytes",
       "legendFormat": "Used Raw"
      },
      { "expr": "ceph_cluster_total_bytes *.85", "legendFormat": "CLUSTER_FULL Threshold (85%)" }
     ]
    },
    {
     "title": "Client IOPS (rbd* devices)",
     "type": "timeseries",
     "description": "Total of IOPS for rbd devices within the cluster",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "round(sum(rate(node_disk_reads_completed_total{device=~\"rbd.*\"}[30s])),1)",
       "legendFormat": "Reads"
      },
      {
       "expr": "round(sum(rate(node_disk_writes_completed_total{device=~\"rbd.*\"}[30s])),1)",
       "legendFormat": "Writes"
      }
     ]
    }
   ]
  },
  {
   "title": "Noobaa Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Noobaa Health",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "NooBaa_health_status" }
     ]
    },
    {
     "title": "Buckets",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count(NooBaa_bucket_status)" }
     ]
    },
    {
     "title": "Buckets in Error",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(noobaa_bucket_status == 0) or vector(0)"
      }
     ]
    },
    {
     "title": "OBCs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "NooBaa_num_buckets_claims" }
     ]
    },
    {
     "title": "Object Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "NooBaa_num_objects_buckets_claims"
      }
     ]
    },
    {
     "title": "Quotas Set",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(NooBaa_bucket_size_quota > 0) or vector(0)"
      }
     ]
    },
    {
     "title": "Savings",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(NooBaa_object_savings_logical_size - NooBaa_object_savings_physical_size) "
      }
     ]
    },
    {
     "title": "Data Reduction",
     "type": "stat",
     "description": "Data reduction ratio",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "NooBaa_reduction_ratio" }
     ]
    },
    {
     "title": "Capacity Used",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 2, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "NooBaa_system_capacity" }
     ]
    },
    {
     "title": "Usage by bucketclass",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "NooBaa_bucket_class_capacity_usage",
       "legendFormat": "{{bucket_class}}"
      }
     ]
    },
    {
     "title": "Total Noobaa CPU Core Usage",
     "type": "timeseries",
     "description": "Sum of Core usage for ALL noobaa daemons",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",container=~\"noobaa|core|db|endpoint\", namespace=\"openshift-storage\"}[1m]))",
       "legendFormat": "Total CPU"
      }
     ]
    },
    {
     "title": "Noobaa Provider R/W OPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum by(namespace, managedBy, job, service) (rate(NooBaa_providers_ops_read_num[1m]))",
       "legendFormat": "Read OPs "
      },
      {
       "expr": "sum by(namespace, managedBy, job, service) (rate(NooBaa_providers_ops_write_num[1m]))",
       "legendFormat": "Write OPs"
      }
     ]
    },
    {
     "title": "Noobaa Provider R/W Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(namespace, managedBy, job, service) (rate(NooBaa_providers_bandwidth_read_size[1m]))",
       "legendFormat": "Read Throughput"
      },
      {
       "expr": "sum by(namespace, managedBy, job, service) (rate(NooBaa_providers_bandwidth_write_size[1m]))",
       "legendFormat": "Write Throughput"
      }
     ]
    },
    {
     "title": "Capacity Used vs Object count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "noobaa_total_usage", "legendFormat": "Total Used" },
      {
       "expr": "job:noobaa_total_object_count:sum",
       "legendFormat": "Object Count"
      }
     ]
    },
    {
     "title": "Object Size Distribution",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "NooBaa_object_histo > 0", "legendFormat": "{{size}}" }
     ]
    }
   ]
  },
  {
   "title": "radosGW Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "RGW Daemons",
     "type": "stat",
     "description": "Count of 'active' radosgw daemons",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ceph_rgw_metadata) or vector(0)"
      }
     ]
    },
    {
     "title": "Radosgw CPU Core Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 2, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(rate(container_cpu_usage_seconds_total{image!=\"\",container=~\"rgw\", namespace=\"openshift-storage\"}[1m]),\"daemon\", \"$1\", \"pod\", \"rook-ceph-(.*)\")",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GET/PUT Throughput - All Instances",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "round(sum(rate(ceph_rgw_get_b[65s])),1)",
       "legendFormat": "GET bytes"
      },
      {
       "expr": "round(sum(rate(ceph_rgw_put_b[65s])),1)",
       "legendFormat": "PUT bytes"
      }
     ]
    },
    {
     "title": "Requests/sec",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum(rate(ceph_rgw_req[1m])),1)"
      }
     ]
    },
    {
     "title": "Q Length",
     "type": "stat",
     "description": "Requests queue length",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "round(avg(ceph_rgw_qlen),1)" }
     ]
    },
    {
     "title": "GET/PUTs - All Instances",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 2, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "round(sum(rate(ceph_rgw_get[65s])),1)",
       "legendFormat": "GET ops"
      },
      {
       "expr": "round(sum(rate(ceph_rgw_put[65s])),1)",
       "legendFormat": "PUT ops"
      }
     ]
    },
    {
     "title": "GET/PUT Latencies - All Instances",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(ceph_rgw_get_initial_lat_sum[1m]) / rate(ceph_rgw_get_initial_lat_count[1m]))",
       "legendFormat": "GET latency"
      },
      {
       "expr": "sum(rate(ceph_rgw_put_initial_lat_sum[1m]) / rate(ceph_rgw_put_initial_lat_count[1m]))",
       "legendFormat": "PUT latency"
      }
     ]
    },
    {
     "title": "Q Active",
     "type": "stat",
     "description": "Active Requests Queue",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "round(avg(ceph_rgw_qactive),1)" }
     ]
    }
   ]
  },
  {
   "title": "Data Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total PGs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(ceph_pg_total)" }
     ]
    },
    {
     "title": "PG Count by Pool",
     "type": "timeseries",
     "description": "This is the primary PG count",
     "gridPos": { "h": 8, "w": 7, "x": 2, "y": 4 },
     "targets": [
      {
       "expr": "ceph_pg_total * on(pool_id) group_left(name) (ceph_pool_metadata)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "PG Distribution ",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      { "expr": "ceph_osd_numpg" }
     ]
    },
    {
     "title": "OSD Usage over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(ceph_osd_stat_bytes_used / ceph_osd_stat_bytes) * 100",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Physical Disk Activity - by Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total IOPS by Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(instance) (rate(node_disk_writes_completed_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\")) + sum by(instance) (rate(node_disk_reads_completed_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\"))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Disk Bandwidth by Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(instance) (rate(node_disk_written_bytes_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\")) + sum by(instance) (rate(node_disk_read_bytes_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\"))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Physical Disk Activity - by OSD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "WRITE IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_writes_completed_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\")",
       "legendFormat": "{{ ceph_daemon  }} / {{ device }}"
      },
      {
       "expr": "sum(rate(node_disk_writes_completed_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\"))",
       "legendFormat": "Total Write IOPS"
      }
     ]
    },
    {
     "title": "WRITE Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_write_time_seconds_total[1m]) / clamp_min(rate(node_disk_writes_completed_total[1m]),1)) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\")",
       "legendFormat": "{{ ceph_daemon  }} / {{ device }}"
      }
     ]
    },
    {
     "title": "WRITE Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(node_disk_written_bytes_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\")",
       "legendFormat": "{{ ceph_daemon  }} / {{ device }}"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\"))",
       "legendFormat": "Total Write Throughput"
      }
     ]
    },
    {
     "title": "Average Write IO Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(rate(node_disk_written_bytes_total[30s]) / rate(node_disk_writes_completed_total[30s]) ) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\")",
       "legendFormat": "{{ceph_daemon}}/{{device}}"
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\")",
       "legendFormat": "{{ ceph_daemon  }} / {{ device }}"
      },
      {
       "expr": "sum(rate(node_disk_reads_completed_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\"))",
       "legendFormat": "Total Read IOPS"
      }
     ]
    },
    {
     "title": "READ Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_read_time_seconds_total[1m]) / clamp_min(rate(node_disk_reads_completed_total[1m]),1)) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\")",
       "legendFormat": "{{ ceph_daemon  }} / {{ device }}"
      }
     ]
    },
    {
     "title": "READ Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\")",
       "legendFormat": "{{ ceph_daemon  }} / {{ device }}"
      },
      {
       "expr": "sum(rate(node_disk_read_bytes_total[1m]) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\"))",
       "legendFormat": "Total READ Throughput"
      }
     ]
    },
    {
     "title": "Average Read IO Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(rate(node_disk_read_bytes_total[30s]) / rate(node_disk_reads_completed_total[30s]) ) * on(instance, device) group_left(ceph_daemon) label_replace(label_replace(ceph_disk_occupation, \"instance\", \"$1\", \"exported_instance\", \"(.*)\"), \"device\", \"$1\", \"device\", \"/dev/(.*)\")",
       "legendFormat": "{{ceph_daemon}}/{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Bandwidth by Host",
     "type": "timeseries",
     "description": "Network receive + transmit bytes for all active (UP) physical interfaces on each host in the cluster",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(sum by(instance) (rate(node_network_receive_bytes_total{device=~\"(eth|en).*\"}[1m]) * on(instance, device) node_network_info{operstate=\"up\"})) +\n(sum by(instance) (rate(node_network_transmit_bytes_total{device=~\"(eth|en).*\"}[1m]) * on(instance, device) node_network_info{operstate=\"up\"}))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Network Load : $worker",
     "type": "timeseries",
     "description": "Network receive + transmit bytes for all active (UP) physical interfaces on each host in the cluster",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(rate(node_network_receive_bytes_total{instance=\"$worker\",device=~\"(eth|en).*\"}[1m]) * on(instance, device) node_network_info{operstate=\"up\"})",
       "legendFormat": "{{device}}/RX"
      },
      {
       "expr": "(rate(node_network_transmit_bytes_total{instance=\"$worker\",device=~\"(eth|en).*\"}[1m]) * on(instance, device) node_network_info{operstate=\"up\"}) * -1",
       "legendFormat": "{{device}}/TX"
      }
     ]
    },
    {
     "title": "NIC Configuration : $worker",
     "type": "table",
     "description": "Links speed and MTU size on physical interfaces in an UP state",
     "gridPos": { "h": 9, "w": 7, "x": 16, "y": 7 },
     "targets": [
      {
       "expr": "node_network_speed_bytes{instance=\"$worker\",device=~\"(eno|eth|ens).*\"} * on(instance,device) node_network_info{operstate=\"up\"}"
      },
      {
       "expr": "node_network_mtu_bytes{instance=\"$worker\",device=~\"(eno|eth|ens).*\"} * on(instance,device) node_network_info{operstate=\"up\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ceph CPU / Memory Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ceph Daemon CPU Usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(container_cpu_usage_seconds_total{image!=\"\",container=~\"osd|rbd-mirror|mgr|mon|mds|rgw\", namespace=\"openshift-storage\"}[1m]),\"daemon\", \"$1\", \"pod\", \"rook-ceph-(.*)\")\n",
       "legendFormat": "{{daemon}}"
      }
     ]
    },
    {
     "title": "Ceph Daemon Memory Utilisation",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "decbytes", "label": "RAM Usage" }
     ],
     "targets": [
      {
       "expr": "label_replace(container_memory_rss{container=~\"osd|rbd-mirror|mgr|mon|mds\", namespace=\"openshift-storage\"},\"daemon\", \"$1\", \"pod\", \"rook-ceph-(.*)\")",
       "legendFormat": "{{daemon}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Noobaa CPU / Memory Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Noobaa Pod CPU Usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(container_cpu_usage_seconds_total{image!=\"\",container=~\"(noobaa|core|db|endpoint).*\", namespace=\"openshift-storage\"}[1m]),\"daemon\", \"$1\", \"pod\", \"noobaa-(.*)\")\n",
       "legendFormat": "{{daemon}}"
      }
     ]
    },
    {
     "title": "Nooba Pod Memory Utilisation",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "decbytes", "label": "RAM Usage" }
     ],
     "targets": [
      {
       "expr": "label_replace(container_memory_rss{container=~\"(noobaa|core|db|endpoint).*\", namespace=\"openshift-storage\"},\"daemon\", \"$1\", \"pod\", \"noobaa-(.*)\")",
       "legendFormat": "{{daemon}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Client Activity : $worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Node RBD Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 129 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(node_disk_read_bytes_total{instance=~\"$worker\", device=~\"rbd.*\"})"
      }
     ]
    },
    {
     "title": "IOPS : $rbd_device",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 2, "y": 129 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{device=~\"$rbd_device\", instance=~\"$worker\"}[1m])",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{device=~\"$rbd_device\", instance=~\"$worker\"}[1m])",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Throughput : $rbd_device",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 7, "y": 129 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{device=~\"$rbd_device\", instance=~\"$worker\"}[30s])",
       "legendFormat": "reads"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{device=~\"$rbd_device\", instance=~\"$worker\"}[30s])",
       "legendFormat": "writes"
      }
     ]
    },
    {
     "title": "Latency : $rbd_device",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 12, "y": 129 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_read_time_seconds_total{instance=\"$worker\", device=~\"$rbd_device\"}[30s]) / clamp_min(rate(node_disk_reads_completed_total[30s]),1))",
       "legendFormat": "read"
      },
      {
       "expr": "(rate(node_disk_write_time_seconds_total{instance=\"$worker\", device=~\"$rbd_device\"}[30s]) / clamp_min(rate(node_disk_writes_completed_total[30s]),1))",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Active RBDs (READ)",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 129 },
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{device=~\"rbd(.*)\", instance=~\"$worker\"}[1m]) > 0"
      }
     ]
    },
    {
     "title": "RBDs Active",
     "type": "stat",
     "description": "Count of rbd images with read activity",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 133 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(rate(node_disk_reads_completed_total{device=~\"rbd(.*)\", instance=~\"$worker\"}[1m]) > 0)"
      }
     ]
    }
   ]
  },
  {
   "title": "PVC Analysis : $pvc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\"}"
      }
     ]
    },
    {
     "title": "PVC IOPS : $pvc",
     "type": "timeseries",
     "description": "Needs the rbd_stats_pools set in mgr/prometheus",
     "gridPos": { "h": 12, "w": 7, "x": 2, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "round(rate(ceph_rbd_read_ops[30s]),1)  * on(image) group_left(volumename) label_replace(ocs_rbd_pv_metadata,\"volumename\",\"$1\",\"name\",\"(.*)\") * on(volumename) group_left(persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=~\"$pvc\"}",
       "legendFormat": "{{persistentvolumeclaim}}(R)"
      },
      {
       "expr": "round(rate(ceph_rbd_write_ops[30s]),1) * on(image) group_left(volumename) label_replace(ocs_rbd_pv_metadata,\"volumename\",\"$1\",\"name\",\"(.*)\") * on(volumename) group_left(persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=~\"$pvc\"}",
       "legendFormat": "{{persistentvolumeclaim}}(W)"
      }
     ]
    },
    {
     "title": "PVC Throughput : $pvc",
     "type": "timeseries",
     "description": "Needs the rbd_stats_pools set in mgr/prometheus",
     "gridPos": { "h": 12, "w": 7, "x": 9, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "round(rate(ceph_rbd_read_bytes[30s]),1)  * on(image) group_left(volumename) label_replace(ocs_rbd_pv_metadata,\"volumename\",\"$1\",\"name\",\"(.*)\") * on(volumename) group_left(persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=~\"$pvc\"}",
       "legendFormat": "{{persistentvolumeclaim}}(R)"
      },
      {
       "expr": "round(rate(ceph_rbd_write_bytes[30s]),1) * on(image) group_left(volumename) label_replace(ocs_rbd_pv_metadata,\"volumename\",\"$1\",\"name\",\"(.*)\") * on(volumename) group_left(persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=~\"$pvc\"}",
       "legendFormat": "{{persistentvolumeclaim}}(W)"
      }
     ]
    },
    {
     "title": "PVC Latency : $pvc",
     "type": "timeseries",
     "description": "Needs the rbd_stats_pools set in mgr/prometheus",
     "gridPos": { "h": 12, "w": 7, "x": 16, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "(rate(ceph_rbd_read_latency_sum[30s]) / clamp_min(rate(ceph_rbd_read_latency_count[30s]),1))  * on(image) group_left(volumename) label_replace(ocs_rbd_pv_metadata,\"volumename\",\"$1\",\"name\",\"(.*)\") * on(volumename) group_left(persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=~\"$pvc\"}",
       "legendFormat": "{{persistentvolumeclaim}}(R)"
      },
      {
       "expr": "(rate(ceph_rbd_write_latency_sum[30s]) / clamp_min(rate(ceph_rbd_write_latency_count[30s]),1))  * on(image) group_left(volumename) label_replace(ocs_rbd_pv_metadata,\"volumename\",\"$1\",\"name\",\"(.*)\") * on(volumename) group_left(persistentvolumeclaim) kube_persistentvolumeclaim_info{persistentvolumeclaim=~\"$pvc\"}",
       "legendFormat": "{{persistentvolumeclaim}}(W)"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "description": "As  reported by kubelet",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc\"}"
      }
     ]
    },
    {
     "title": "PVC Utilisation",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Extras",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client IOPS - ALL rbd images",
     "type": "timeseries",
     "description": "Total of IOPS for rbd devices within the cluster",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum(rate(node_disk_reads_completed_total{device=~\"rbd.*\"}[30s]))",
       "legendFormat": "Reads"
      },
      {
       "expr": "sum(rate(node_disk_writes_completed_total{device=~\"rbd.*\"}[30s]))",
       "legendFormat": "Writes"
      }
     ]
    }
   ]
  }
 ]
}