{
 "title": "POD Analysis",
 "time": { "from": "2022-09-21T22:45:00.000Z", "to": "2022-09-22T00:45:59.000Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "pod_namespace", "label": "POD Namespace", "query": "warp" },
   { "name": "pod_prefix", "label": "POD prefix", "query": "warp-(0|1|2)" }
  ]
 },
 "panels": [
  { "title": "POD Performance Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage for $pod_namespace/$pod_prefix Pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"$pod_namespace\",pod=~\"${pod_prefix}.*\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RAM Usage (RSS) for $pod_namespace/$pod_prefix Pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_rss{namespace=\"$pod_namespace\",pod=~\"${pod_prefix}.*\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Throughput for $pod_namespace/$pod_prefix  Pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$pod_namespace\",pod=~\"${pod_prefix}.*\"}[1m])",
     "legendFormat": "{{pod}}-RX"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$pod_namespace\",pod=~\"${pod_prefix}.*\"}[1m]) * -1",
     "legendFormat": "{{pod}}-TX"
    }
   ]
  },
  {
   "title": "Disk IOPS (R+W) for $pod_namespace/$pod_prefix  Pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "round(sum by(pod) (rate(container_fs_reads_total{namespace=~\"$pod_namespace\",pod=~\"${pod_prefix}.*\"}[1m]) + rate(container_fs_writes_total{namespace=~\"$pod_namespace\",pod=~\"${pod_prefix}.*\"}[1m])),1)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Throughput(R+W) for $pod_namespace/$pod_prefix  Pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "round(sum by(pod) (rate(container_fs_reads_bytes_total{namespace=~\"$pod_namespace\",pod=~\"${pod_prefix}.*\"}[1m]) + rate(container_fs_writes_bytes_total{namespace=~\"$pod_namespace\",pod=~\"${pod_prefix}.*\"}[1m])),1)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Write IO Sizes for $pod_namespace/$pod_prefix Pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{namespace=~\"$pod_namespace\",pod=~\"${pod_prefix}.*\"}[1m]) / clamp_min(rate(container_fs_writes_total{namespace=~\"$pod_namespace\",pod=~\"${pod_prefix}.*\"}[1m]),1)",
     "legendFormat": "{{pod}}:{{device}}"
    }
   ]
  },
  {
   "title": "Read IO Sizes for $pod_namespace/$pod_prefix Pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{namespace=~\"$pod_namespace\",pod=~\"${pod_prefix}.*\"}[1m]) / clamp_min(rate(container_fs_reads_total{namespace=~\"$pod_namespace\",pod=~\"${pod_prefix}.*\"}[1m]),1)",
     "legendFormat": "{{pod}}:{{device}}"
    }
   ]
  }
 ]
}